version: "3.8"

services:
  db:
    container_name: db-cryptography
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: purchases
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - purchase-network

  api-reports:
    build: .
    container_name: api-purchase
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/purchases
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    networks:
      - purchase-network

volumes:
  postgres_data:

networks:
  purchase-network:
    driver: bridge
